http:
  addr: ":8080"

redis:
  addr: "localhost:6379"
  password: "123456"

db:
  driver: "mysql"
  dsn: "root:jayleonc@tcp(localhost:3306)/ser-logs?charset=utf8&parseTime=true"

kafka:
  addrs:
    - "localhost:9094"

etcd:
  addresses:
    - "127.0.0.1:2379"
#    - "127.0.0.2:2379"
#    - "127.0.0.3:2379"
